language: node
dist: xenial
os: linux

cache:
  - yarn

rust:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_a11d45963b96_key -iv $encrypted_a11d45963b96_iv
    -in dpl.key.enc -out dpl.key -d

before_script:
  - (test -x node_modules || yarn install)

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

script:
  - rm -rf out && yarn build && yarn test

deploy:
  provider: pages
  cleanup: false
  deploy_key: "./dpl.key"
  local_dir: "./book"
  keep_history: true
  edge: true
  target_branch: gh-pages
  name: Travis CI
  email: deploy@travis-ci.org
