[book]
authors = ["The Puzzlemaker", "Alec Petridis", "Vexillologists VecCTF Team"]
language = "en"
multilingual = false
src = "src"
title = "VexCTF Specification"
description = "The (semi-)formal specifiation for VexCTF, a GraphQL-based API for CTF hosting."

[build]
create-missing = true

[output.html]
mathjax-support = true
default-theme = "coal"
curly-quotes = true
git-repository-url = "https://github.com/Vexillologists/VexCTF-spec.git"
additional-js = ["src/fontawesome5kit.js"]

[output.html.fold]
enable = true
level = 2

[output.html.playpen]
editable = true
line-numbers = true

[output.html.search]
use-boolean-and = true
boost-hierarchy = 2
expand = true
heading-split-level = 2

[rust]
edition = "2018"
