# Challenge types and queries/mutations

"""
A CTF challenge.
"""
type Challenge implements Node {
  """
  The challenge's category
  """
  category: Category!
  
  """
  The challenge's description
  """
  challengeDescription: String!
  
  """
  The challenge's case-insensitive name
  """
  challengeName: String!
  
  """
  Whether or not the challenge's flag is case-sensitive
  """
  flagCaseSensitive: Boolean!
  
  """
  The challenge's hints.
  """
  hints(
    """
    Get the first N items after `after`
    """
    first: Int

    """
    Get the last N items before `before`
    """
    last: Int

    """
    Get values before a cursor
    """
    before: String
    
    """
    Get values after a cursor
    """
    after: String
  ): HintConnection
  
  """
  The opaque ID of the object. Usually base64 encoded.
  """
  id: ID!

  """
  The challenge's point value
  """
  points: Int!
}

"""
A CTF challenge category.
"""
type Category implements Node {
  """
  The category's description
  """
  categoryDescription: String!

  """
  The category's case-insensitive name
  """
  categoryName: String!

  """
  This category's challenges
  """
  challenges(
    """
    Get the first N items after `after`
    """
    first: Int

    """
    Get the last N items before `before`
    """
    last: Int

    """
    Get values before a cursor
    """
    before: String
    
    """
    Get values after a cursor
    """
    after: String
  ): ChallengeConnection

  """
  The opaque ID of the object. Usually base64 encoded.
  """
  id: ID!
}

"""
Look up challenges
"""
type ChallengeConnection {
  """
  A list of edges.
  """
  edges: [ChallengeEdge!]!

  """
  Information to aid in pagination.
  """ 
  pageInfo: PageInfo!

  """
  Identifies the total count of items in the connection.
  """
  totalCount: Int!
}


"""
An edge in a connection.
"""
type ChallengeEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!
  
  """
  The item at the end of the edge.
  """
  node: Challenge!
}

"""
Look up hints
"""
type HintConnection {
  """
  A list of edges.
  """
  edges: [HintEdge!]!

  """
  Information to aid in pagination.
  """ 
  pageInfo: PageInfo!

  """
  Identifies the total count of items in the connection.
  """
  totalCount: Int!
}


"""
An edge in a connection.
"""
type HintEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!
  
  """
  The item at the end of the edge.
  """
  node: String!
}
