# Scoreboard types and queries

"""
Look up the scoreboard
"""
type ScoreboardConnection {
  """
  A list of edges.
  """
  edges: [ScoreboardEdge!]!

  """
  The maximum number of points possible.
  """
  maxPoints: Int!

  """
  Information to aid in pagination.
  """ 
  pageInfo: PageInfo!

  """
  Identifies the total count of items in the connection.
  """
  totalCount: Int!

  """
  Your team's scoreboard placing, if you are on one.
  """
  you: ScoreboardEdge
}

"""
An edge in a connection.
"""
type ScoreboardEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!
  
  """
  The item at the end of the edge.
  """
  node: ScoreboardTeam!
}

"""
A team on the scoreboard
"""
type ScoreboardTeam implements Node {
  """
  The opaque ID of the object. Usually base64 encoded. Equal to base64.encoded(`ScoreboardTeam:${base64.decoded(team.id)}`)
  """
  id: ID!

  """
  The team's place on the leaderboard
  """
  place: Int!
  
  """
  The team's object
  """
  team: Team!
}

extend type Query {
  """
  Look up the scoreboard
  """
  scoreboard(
    """
    Get the first N items after `after`
    """
    first: Int

    """
    Get the last N items before `before`
    """
    last: Int

    """
    Get values before a cursor
    """
    before: String
    
    """
    Get values after a cursor
    """
    after: String
  ): ScoreboardConnection
}