# Session types

"""
A session token in the form of a JSON Web Token (JWT).
It may contain any application-specific data.
All requests require authentication unless specified.

The JWT payload contains the following fields:
{
  exp: The expiry time (usually 36 hours from assignment),
  jti: The internal session ID, in any form,
  uid: The user's Node ID
}
"""
scalar SessionToken
