# Team types and queries/mutations

"""
A CTF team.
"""
type Team implements Node {
  """
  The opaque ID of the object. Usually base64 encoded.
  """
  id: ID!

  """
  The team's members
  """
  members(
    """
    Get the first N items after `after`
    """
    first: Int

    """
    Get the last N items before `before`
    """
    last: Int

    """
    Get values before a cursor
    """
    before: String
    
    """
    Get values after a cursor
    """
    after: String
  ): UserConnection

  """
  The team's current amount of points
  """
  points: Int!
  
  """
  The team's solves
  """
  solves(
    """
    Get the first N items after `after`
    """
    first: Int

    """
    Get the last N items before `before`
    """
    last: Int

    """
    Get values before a cursor
    """
    before: String
    
    """
    Get values after a cursor
    """
    after: String
  ): ChallengeConnection
  
  """
  The team's case-insensitive name
  """
  teamName: String!
}