# User types and queries/mutations

"""
A CTF user.
"""
type User implements Node {
  """
  The opaque ID of the object. Usually base64 encoded.
  """
  id: ID!

  """
  The user's team
  """
  team: Team
  
  """
  The user's case-insensitive name
  """
  username: String!
}


"""
Look up edges
"""
type UserConnection {
  """
  A list of edges.
  """
  edges: [UserEdge!]!

  """
  Information to aid in pagination.
  """ 
  pageInfo: PageInfo!

  """
  Identifies the total count of items in the connection.
  """
  totalCount: Int!
}


"""
An edge in a connection.
"""
type UserEdge {
  """
  A cursor for use in pagination.
  """
  cursor: String!
  
  """
  The item at the end of the edge.
  """
  node: User!
}